name: Tests de conformité avec ESLint

on:
    push:
        branches:
            - main
            - develop
    pull_request:
        branches:
            - '*'

jobs:
    eslint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Run conformance tests
              run: npm run lint
